version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
      - "8404:8404"

  serverA:
    image: httpd:latest
    volumes:
      - ./serverA:/usr/local/apache2/htdocs/
    ports:
      - "8081:80"

  serverB:
    image: httpd:latest
    volumes:
      - ./serverB:/usr/local/apache2/htdocs/
    ports:
      - "8082:80"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana

  haproxy-exporter:
    image: prom/haproxy-exporter
    ports:
      - "9101:9101"
    command:
      - --haproxy.scrape-uri=http://admin:password@haproxy:8404/stats;csv
      - --haproxy.timeout=10s
    depends_on:
      - haproxy
